name: protalignARG
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - biopython=1.85
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - expat=2.7.1
  - hdf5=1.14.3
  - joblib=1.5.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libaec=1.1.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.5.2
  - pandas=2.3.2
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.15
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - readline=8.3
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.4
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fsspec==2025.7.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.10
      - jinja2==3.1.4
      - keras==3.11.3
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - namex==0.1.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pillow==11.0.0
      - protobuf==6.32.0
      - pygments==2.19.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - rich==14.1.0
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - tokenizers==0.21.4
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - transformers==4.55.4
      - triton==3.4.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
